run:
  build-tags:
    - unit
    - integration
  skip-files:
    - driver/inmemory/matcher_gen.go

linters:
  enable:
    - maligned
    - deadcode
    - errcheck
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - ineffassign
    - interfacer
    - staticcheck
    - structcheck
    - unconvert
    - varcheck
    - vet
    - vetshadow

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
