run:
  build-tags:
    - unit
    - integration
  skip-files:
    - driver/inmemory/matcher_gen.go

linters:
  enable:
    - maligned
    - deadcode
    - errcheck
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - ineffassign
    - interfacer
    - staticcheck
    - structcheck
    - unconvert
    - varcheck
    - vet
    - vetshadow

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    # Ignore the streamEvents.Close errcheck warning since we do not want to introduce a logger for repositories just yet
    - path: aggregate/repository.go
      text: "Error return value of \\`streamEvents.Close\\` is not checked"
      linters:
        - errcheck
