language: go
go:
  - "1.10.x"
  - "1.11.x"
  - master
dist: xenial
addons:
  postgresql: "10"
cache:
  directories:
    - $HOME/gopath/pkg/mod
env:
  global:
    - POSTGRES_DSN="postgres://postgres@localhost:5432/goengine?sslmode=disable&client_encoding=UTF8"

matrix:
  allow_failures:
    - go: master

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure -v

before_script:
  - psql -U postgres -c "CREATE DATABASE goengine ENCODING 'UTF8';"

script:
  - go test -tags=unit -race ./...
  - go test -tags=integration -race ./...
  - go run -race example/aggregate/*.go
  - go run -race example/repository/*.go

