[package]
name = "canonicaljson-rs"
version = "1.0.0"
authors = ["Mathieu Leplatre <mathieu@mozilla.com>"]
edition = "2018"

[lib]
name = "canonicaljson"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"

[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]
