[tool.poetry]
name = "pySigma-backend-loki"
version = "0.1.0"
description = "pySigma Loki backend"
authors = ["Nick Moore <nicholas.moore@grafana.com>"]
license = "Apache-2.0"
repository = "https://github.com/kelnage/pySigma-backend-loki"
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = "^3.8"
pysigma = "^0.8.9"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
coverage = "^6.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
