# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.17.185123'

RELEASE_GIT_HEAD = '6f3011c53edf30fe1ce66563a57d350b5bb8fddc'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
