name: publish_to_pages_staging
description: Publish to cloudflare pages (Staging)
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account id'
    required: true
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare token'
    required: true
runs:
  using: composite
  steps:
  - name: Publish to cloudflare pages (staging)
    run: |-
      cd dist
      npx wrangler pages deploy . --project-name=deriv-binary-static-pages --branch=staging
      echo "New staging website - http://staging.cf-pages-deriv-binary-static.deriv.com"
    shell: bash
