name: send_slack_notifications
description: Send Slack notification
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook URL'
    required: true
  status:
    description: 'Job status'
    required: true
  release_type:
    description: 'Release type'
    required: true
  version:
    description: 'Version'
    required: true
    default: 'N/A'
runs:
  using: composite
  steps:
    - name: Send Slack Notification on Success
      env:
        RELEASE_TYPE: ${{ inputs.RELEASE_TYPE }}
        VERSION: ${{ inputs.VERSION }}
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      if: inputs.status == 'success'
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "${RELEASE_TYPE} Release succeeded for smarttrader.deriv.com with version ${VERSION}"
        }' \
          ${SLACK_WEBHOOK_URL}
      shell: bash

    - name: Send Slack Notification on Failure
      env:
        RELEASE_TYPE: ${{ inputs.RELEASE_TYPE }}
        VERSION: ${{ inputs.VERSION }}
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
      if: inputs.status == 'failure'
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
          "text": "${RELEASE_TYPE} Release failed for smarttrader.deriv.com with version ${VERSION}"
        }' \
        $SLACK_WEBHOOK_URL
      shell: bash
