name: DSmartTrader Staging Release
on:
  push:
    branches:
    - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.22
    - name: Install dependencies
      uses: "./.github/actions/npm_install"
    - name: Build
      uses: "./.github/actions/build"
      with:
        target: production
    - uses: "./.github/actions/versioning"
      with:
        target_branch: production
    - name: "Run Tests"
      run: npm run test
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
  publish_cloudflare_production:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - uses: actions/download-artifact@v3.0.2
      with:
        path: dist
    - uses: "./.github/actions/publish_to_pages_production"
