name: DSmartTrader Test
on:
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: node:12.22.7
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      uses: "./.github/actions/npm_install"
    - name: Build
      uses: "./.github/actions/build"
      with:
        target: production
    - name: "Run Tests"
      run: npm run test
