name: DSmartTrader Test
on:
  pull_request:
    branches:
      - master
jobs:
  release_production:
    runs-on: ubuntu-latest
    container:
      image: node:12.22.7
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/npm_install"
    - uses: "./.github/actions/build"
      with:
        target: production
    - name: "Run Tests"
      run: npm run test
